In [1]:
import os,sys,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)
from bert_embedder import BertEmbedder
import math
from tqdm import tqdm
bert = BertEmbedder('../models/bert/bert-base-uncased')

Init BERT, max_seq_length=128


In [2]:
s = 'foo bar'
# s1 = 'there should be another and another and lots of meaningless word in here I don;t know what to say anymore, bal balbka blash efefeffefef fwff'

In [10]:
vecs1 = bert.embed_v1([s])
vecs1[0].shape

(768,)

In [11]:
vecs2 = bert.embed_v2([s])
vecs2[0].shape

(768,)

In [12]:
vecs3 = bert.embed_v3([s])
vecs3[0].shape

(768,)

In [1]:
import os,sys,inspect
current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parent_dir = os.path.dirname(current_dir)
sys.path.insert(0, parent_dir)
from bert_embedder import BertEmbedder
from pyserini import collection, index
from tqdm import tqdm
from utils import *
from bert_embedder import BertEmbedder
import math
from tqdm import tqdm
import h5py
import pickle

In [3]:
import numpy as np
import os
datadir = os.path.join('..', 'data', 'msmarco-queries-vecs-128.npy')
npy = np.load(datadir, allow_pickle=True)
data = npy.item()
print('number of queries: ', len(data))

number of queries:  5193


In [1]:
import faiss
res = faiss.StandardGpuResources()

# build a flat (CPU) index
d=3
index_flat = faiss.IndexFlatL2(d) 
# make it into a gpu index
gpu_index_flat = faiss.index_cpu_to_gpu(res, 0, index_flat)

In [3]:


import numpy as np
xb = [
    [1,2,1],
    [1,2,2],
    [90,78,500],
]

xb1 = [
    [1,2,1]
]
xb2 = [
    [1,2,2]
]
xb3 = [
    [90,78,500]
]

xb1 = np.array(xb1, dtype=np.float32)
xb2 = np.array(xb2, dtype=np.float32)
xb3 = np.array(xb3, dtype=np.float32)
gpu_index_flat.add(xb1)         # add vectors to the index
gpu_index_flat.add(xb2) 
gpu_index_flat.add(xb3) 
print(gpu_index_flat.ntotal)

3


In [4]:
k = 3                          # we want to see 4 nearest neighbors
xq = np.array([[1,2,2]], dtype=np.float32)
D, I = gpu_index_flat.search(xq, k)  # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:]) 

[[1 0 2]]
[[1 0 2]]


In [7]:
I

array([[1, 0, 2]])

In [8]:
D

array([[0.00000e+00, 1.00000e+00, 2.61701e+05]], dtype=float32)